### ISSUE TITLE
appx Installer has Untrusted Certificate

### ISSUE THREAD

**Issue by AngellusMortis** [Voxelum/x-minecraft-launcher#590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

v0.40.0+

### Operating System

Windows

### Architecture

x64

### Current Behavior

It seems like any version of the launcher past v0.39.17 is not able to be installed on Windows. The appx installer package has an untrusted certificate. This also causes auto-update to break as well.

### Expected Behavior

appx / auto-update should work

### Steps To Reproduce

1. Download appx installer for version newer then v0.39.17
2. Attempt to install

**Comment by ci010** [comment]
My code sign certificate is expired, and due to the new policy, the OV certifiacte cannot sign without hardware token device. So the current pipeline won't work anymore.

I'm currently applying the code sign from signpath. The signpath will support the github action in one month.

I think after the signpath github action is GA, we can bring the appx back.

**Comment by Soham52** [comment]
I know that you must be trying to fix this, but when will this be fixed?

**Comment by Soham52** [comment]
> My code sign certificate is expired, and due to the new policy, the OV certifiacte cannot sign without hardware token device. So the current pipeline won't work anymore.
> 
> I'm currently applying the code sign from signpath. The signpath will support the github action in one month.
> 
> I think after the signpath github action is GA, we can bring the appx back.

I know that you must be trying to fix this, but when will this be fixed?

**Comment by ci010** [comment]
I'm on the waitlist of Sign Path. It seems the https://github.com/SignPath/github-actions is already stable. I will send an email to apply the certificate again.

**Comment by NAKADZI** [comment]
@ci010 It's been a month since your last reply, and more than two months since the **APPX** packaging disappeared if I'm not mistaken. 
Have you still not received a certificate?

I think it would be better to get rid of the **APPX** packaging in favor of the simpler [Winget](https://github.com/microsoft/winget-cli) packaging and delivery method (_which is integrated in modern versions of Windows 10/11_), or use it as an alternative option alongside **APPX** packaging.

**Comment by ci010** [comment]
I've submit the form to signpath.io and for some reason I still didn't get reply yet. I will ping the contact again if there is no reply this week

**Comment by Soham52** [comment]
@ci010 Did you get a reply yet?

**Comment by Soham52** [comment]
@ci010 Haven't you received a reply yet?

**Comment by ci010** [comment]
> @ci010 Haven't you received a reply yet?

I got the signpath certificate, but it's currently still beta, which mean it can only sign for testing not for production. We still need to wait it ready for production singing.

**Comment by Soham52** [comment]
@ci010 Has there been any progress?

**Comment by ci010** [comment]
> @ci010 Has there been any progress?

We already implement the POC build pipeline with signpath test certificate (see branch https://github.com/Voxelum/x-minecraft-launcher/tree/signpath and its action https://github.com/Voxelum/x-minecraft-launcher/actions/runs/10026514240).

Currently we are waiting signpath to release the https://github.com/SignPath/github-action-submit-signing-request so we can use the release certificate to sign appx.

**Comment by ci010** [comment]
Some updates.

I've communicated with SignPath's staff and got the reply that they might be GA on mid Aug.

**Comment by Soham52** [comment]
@ci010 Glad to hear that ^^. But what took them so long.

**Comment by Soham52** [comment]
Any update @ci010 ?

**Comment by Soham52** [comment]
Any updates @ci010 ?

**Comment by ci010** [comment]
In new version, appx is avaiable. This issue can be closed
